export default {
    ADD_EDUCATION: 'ADD_EDUACATION',
    EDIT_EDUCATION: 'EDIT_EDUCATION',
    DELETE_EDUCATION: 'DELETE_EDUCATION',
    ADD_EMPLOYMENT: 'ADD_EMPLOYMENT',
    DELETE_EMPLOYMENT: 'DELETE_EMPLOYMENT',
    EDIT_EMPLOYMENT: 'EDIT_EMPLOYMENT',
    LOGIN: 'LOGIN',
    LOGOUT: "LOGOUT",
    ISACTIVE: 'ISACTIVE',
    ISLOGIN: "ISLOGIN",
    JOBS_LOADING: "JOBS_LOADING",
    LOAD_JOBS: "LOAD_JOBS",
    UPDATE_USER_INFO: "UPDATE_USER_INFO",
    FETCHING_JOBS: "FETCHING_JOBS",
    ADD_SKILL: "ADD_SKILL",
    REMOVE_SKILL: "REMOVE_SKILL",
    LOGIN_ERROR: 'LOGIN_ERROR'


}